import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import testcrud.KoneksiDB;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author A455L
 */
public class frmMain extends javax.swing.JFrame {
        String nol_menit = "";
        String nol_detik = "";
        String nol_jam = "";
    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtKelas = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtNIS = new javax.swing.JTextField();
        rdLaki = new javax.swing.JRadioButton();
        rdPerempuan = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1Data = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        txtAlamat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtEmail1 = new javax.swing.JTextField();
        txtKelas1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTempatLahir = new javax.swing.JTextField();
        Tanggal = new com.toedter.calendar.JDateChooser();
        labeljam = new javax.swing.JLabel();
        labeltanggal = new javax.swing.JLabel();
        labeljam1 = new javax.swing.JLabel();
        labeltanggal1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("BIODATA SISWA SMK TELKOM MALANG");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 10, 500, 40);

        jLabel2.setFont(new java.awt.Font("Vivaldi", 0, 36)); // NOI18N
        jLabel2.setText("Widyaloka Kusuma Samekta Makarya");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 50, 540, 30);

        jLabel3.setText("NIS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 84, 50, 50);

        jLabel4.setText("Nama");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 134, 50, 50);

        jLabel5.setText("Alamat");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 560, 90, 50);

        jLabel6.setText("Email");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 480, 80, 50);

        jLabel7.setText("Kelas");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 410, 60, 50);

        jLabel8.setText("Jenis Kelamin");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 200, 120, 50);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(20, 520, 200, 40);
        getContentPane().add(txtKelas);
        txtKelas.setBounds(20, 450, 200, 40);
        getContentPane().add(txtNama);
        txtNama.setBounds(20, 170, 200, 40);
        getContentPane().add(txtNIS);
        txtNIS.setBounds(20, 120, 200, 30);

        rdLaki.setText("Laki-laki");
        rdLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdLakiActionPerformed(evt);
            }
        });
        getContentPane().add(rdLaki);
        rdLaki.setBounds(20, 230, 120, 40);

        rdPerempuan.setText("Perempuan");
        getContentPane().add(rdPerempuan);
        rdPerempuan.setBounds(150, 230, 110, 40);

        tb1Data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama", "Jenis Kelamin", "Tempat Lahir", "Tanggal Lahir", "Kelas", "Email", "null"
            }
        ));
        tb1Data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1DataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb1Data);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(260, 200, 530, 390);

        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(630, 630, 80, 30);

        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(530, 630, 90, 30);

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(440, 630, 80, 30);

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(340, 630, 90, 30);

        jButton5.setText("Save");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(250, 630, 80, 30);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(510, 54, 0, 10);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 810, 90);

        jButton6.setText("Print");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(720, 630, 55, 30);
        getContentPane().add(txtAlamat);
        txtAlamat.setBounds(20, 600, 200, 70);

        jLabel10.setText("Email");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 480, 80, 50);

        jLabel11.setText("Kelas");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 410, 60, 50);
        getContentPane().add(txtEmail1);
        txtEmail1.setBounds(20, 520, 200, 40);
        getContentPane().add(txtKelas1);
        txtKelas1.setBounds(20, 450, 200, 40);

        jLabel12.setText("Tanggal Lahir");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 340, 80, 50);

        jLabel13.setText("Tempat Lahir");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 260, 170, 50);

        txtTempatLahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTempatLahirActionPerformed(evt);
            }
        });
        getContentPane().add(txtTempatLahir);
        txtTempatLahir.setBounds(20, 300, 200, 40);
        getContentPane().add(Tanggal);
        Tanggal.setBounds(20, 380, 200, 40);
        getContentPane().add(labeljam);
        labeljam.setBounds(670, 140, 130, 30);
        getContentPane().add(labeltanggal);
        labeltanggal.setBounds(660, 110, 130, 30);

        labeljam1.setText("Pukul :");
        getContentPane().add(labeljam1);
        labeljam1.setBounds(580, 140, 130, 30);

        labeltanggal1.setText("Tanggal :");
        getContentPane().add(labeltanggal1);
        labeltanggal1.setBounds(570, 110, 130, 30);

        setBounds(0, 0, 823, 720);
    }// </editor-fold>//GEN-END:initComponents

    private void rdLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdLakiActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       selectData();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public void selectData(){
        String kolom[] = {"NIS", "NamaSiswa", "JenisKelamin", "Kelas", "Email", "Alamat"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM t_siswa";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while(rs.next()){
            String NIS = rs.getString(1);
            String NamaSiswa = rs.getString(2);
            String JenisKelamin = "";
            if("L".equals(rs.getString(3))){
            JenisKelamin = "Laki-laki";
            }else{
            JenisKelamin = "Perempuan";
            }
            String Kelas = rs.getString(4);
            String Email = rs.getString(5);
            String Alamat = rs.getString(6);
            String data[] = {NIS,NamaSiswa,JenisKelamin,Kelas,Email,Alamat};
            dtm.addRow(data);
            }
        } catch (SQLException ex){
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE,null,ex);
        } 
        tb1Data.setModel(dtm);
    }
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(Tanggal.getDate());
        String JK = "";
        if(rdLaki.isSelected())
        JK = "L";
     
        if(rdPerempuan.isSelected())
            JK = "P";
            
        
        if(txtNIS.getText().equals("") || txtNama.getText().equals("") || 
            tanggal.equals("") || JK.equals("") || txtKelas.getText().equals("") || txtEmail.getText().equals("") || 
            txtTempatLahir.getText().equals("") || txtAlamat.getText().equals("")){
            
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);        
        } else {
        String SQL = "INSERT INTO t_siswa (NIS, NamaSiswa, JenisKelamin, Kelas, Email, Alamat)" + 
        "VALUES ('"+txtNIS.getText()+"', '"+txtNama.getText()+"', '"+JK+"', '"
                +txtKelas.getText()+"', '"+txtEmail.getText()+"', '"+ txtTempatLahir.getText() + "', '"+txtAlamat.getText()+"')";
        
         int status = KoneksiDB.execute(SQL);
        if (status == 1){
        JOptionPane.showMessageDialog(this,"Berhasil","Sukses",JOptionPane.INFORMATION_MESSAGE);
        selectData();
        } else {
        JOptionPane.showMessageDialog(this,"Tidak berhasil","Gagal", JOptionPane.WARNING_MESSAGE);
        }
     }      
       
        //String SQL = "INSERT INTO t_siswa(NIS, NamaSiswa, JenisKelamin, Kelas, Email, Alamat)" 
               // + "VALUES('"+txtNIS.getText()+"','"+txtNama.getText()+"','"+JK+"',"
                // + "'"+txtKelas.getText()+"','"+txtEmail.getText()+"','"+txtAlamat.getText()+"')";
       
      
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int baris = tb1Data.getSelectedRow();
        if(baris != -1){
            String NIS = tb1Data.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM t_siswa WHERE NIS ='"+NIS+"'";
            int status = KoneksiDB.execute(SQL);
           if (status == 1){
        JOptionPane.showMessageDialog(this,"Berhasil","Sukses",JOptionPane.INFORMATION_MESSAGE);
        } else {
        JOptionPane.showMessageDialog(this,"Tidak berhasil","Gagal", JOptionPane.WARNING_MESSAGE);
        }   
      }else{
        JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih dulu", "Eror", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        txtNIS.setText("");
        txtNama.setText("");
        txtKelas.setText("");
        txtEmail.setText("");
        txtAlamat.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(Tanggal.getDate());
        // TODO add your handling code here:
        if("".equals(txtNIS.getText()) || "".equals(txtAlamat.getText()) ||"".equals(txtKelas.getText()) || "".equals(txtNama.getText()) || "".equals(txtEmail.getText())){
        JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
        String JK = "";
        if(rdLaki.isSelected()){
        JK = "L";
        }else{
        JK = "P";
        }
        
        String SQL = "UPDATE tb_siswa SET "
                + "NamaSiswa='"+txtNama.getText()+"',"+ "JenisKelamin='"+JK+"',"
                + "TanggalLahir='"+tanggal+"',"
                + "TempatLahir='"+txtTempatLahir.getText()+"',"
                + "Kelas='"+txtKelas.getText()+","+ "Email='"+txtEmail.getText()+"'"
                + "Alamat='"+txtAlamat.getText()+"'"
                + "NIS='"+txtNIS.getText()+"'";
            int status = KoneksiDB.execute(SQL);
            if(status == 0){
                JOptionPane.showMessageDialog(this, "Berhasil","Sukses", JOptionPane.INFORMATION_MESSAGE); 
            } else {
                JOptionPane.showMessageDialog(this,"Tidak berhasil","Gagal", JOptionPane.WARNING_MESSAGE);
            }
}                        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tb1DataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1DataMouseClicked
        // TODO add your handling code here:
        int baris = tb1Data.getSelectedRow();
        if(baris != -1){
        txtNIS.setText(tb1Data.getValueAt(baris, 0).toString());
        txtNama.setText(tb1Data.getValueAt(baris, 1).toString());
        if("Laki-laki".equals(tb1Data.getValueAt(baris, 2).toString())){
        rdLaki.setSelected(true);
        } else{
        rdPerempuan.setSelected(true);
        }    
        txtKelas.setText(tb1Data.getValueAt(baris, 3).toString());
        txtEmail.setText(tb1Data.getValueAt(baris, 4).toString());
        txtAlamat.setText(tb1Data.getValueAt(baris, 5).toString());        
        }
    }//GEN-LAST:event_tb1DataMouseClicked

    private void txtTempatLahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTempatLahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTempatLahirActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        MessageFormat header = new MessageFormat ("Biodata Siswa SMK Telkom Malang");
        MessageFormat footer = new MessageFormat ("Page (0,number,integer");
        
        try{
        tb1Data.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e){
        System.err.format("Can't print data", e.getMessage());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    
    public void setTanggal(){
    java.util.Date skrg =  new java.util.Date();
    java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd/MM/yyyy");
    labeltanggal.setText(kal.format(skrg));
    }
    
    public void SetJam(){
        ActionListener taskPerformer = new ActionListener() {
        public void actionPerformed(ActionEvent evt){
        Date dt = new Date();
        int nilai_jam = dt.getHours();
        int nilai_menit = dt.getMinutes();
        int nilai_detik =  dt.getSeconds();
        
        if (nilai_jam <= 9){
        nol_jam = "0";
        }
        
        if (nilai_jam <= 9){
        nol_menit = "0";
        }
        
        if (nilai_jam <= 9){
        nol_detik = "0";
        }
        
        String jam = nol_jam + Integer.toString(nilai_jam);
        String menit = nol_menit + Integer.toString(nilai_jam);
        String detik = nol_detik + Integer.toString(nilai_jam);
        labeljam.setText("Jam "+jam+ ":" + menit + ":" + detik);
        }
        };
        new Timer(100, taskPerformer).start();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Tanggal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labeljam;
    private javax.swing.JLabel labeljam1;
    private javax.swing.JLabel labeltanggal;
    private javax.swing.JLabel labeltanggal1;
    private javax.swing.JRadioButton rdLaki;
    private javax.swing.JRadioButton rdPerempuan;
    private javax.swing.JTable tb1Data;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtKelas;
    private javax.swing.JTextField txtKelas1;
    private javax.swing.JTextField txtNIS;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTempatLahir;
    // End of variables declaration//GEN-END:variables
}
